on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Test

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-14
    steps:
      - name: brew tap
        run: brew tap messense/macos-cross-toolchains
      - name: brew install
        run: |
          brew install \
            x86_64-unknown-linux-gnu \
            aarch64-unknown-linux-gnu \
      - name: brew linkage
        run: |
          brew linkage --test --strict \
            x86_64-unknown-linux-gnu \
            aarch64-unknown-linux-gnu \
